/*!
 * @file JointState.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _SENSOR_MSGS_JOINT_STATE_HPP_
#define _SENSOR_MSGS_JOINT_STATE_HPP_

#include "Pose.hpp"
#include <string>
#include <vector>

namespace sensor_msgs {

class Imu {
  public:
    geometry_msgs::Quaternion orientation;
    double orientation_covariance[9];
    geometry_msgs::Vector3 angular_velocity;
    double angular_velocity_covariance[9];
    geometry_msgs::Vector3 linear_acceleration;
    double linear_acceleration_covariance[9];
};

class JointState {
  public:
    std::vector<std::string> name;
    uint32_t name_size;
    std::vector<double> position;
    uint32_t position_size;
    std::vector<double> velocity;
    uint32_t velocity_size;
    std::vector<double> effort;
    uint32_t effort_size;

    JointState() : name_size(1), position_size(1), velocity_size(1), effort_size(1) {
        // memset(name, 0, sizeof(name));
        // memset(position, 0, sizeof(position));
        // memset(velocity, 0, sizeof(velocity));
        //  memset(effort, 0, sizeof(effort));
    }
};

} // namespace sensor_msgs

#endif // _SENSOR_MSGS_JOINT_STATE_HPP_
