// Generated by gencpp from file syropod_highlevel_controller/LegState.msg
// DO NOT EDIT!

#ifndef SYROPOD_HIGHLEVEL_CONTROLLER_MESSAGE_LEGSTATE_H
#define SYROPOD_HIGHLEVEL_CONTROLLER_MESSAGE_LEGSTATE_H

#include <memory>
#include <string>
#include <vector>

#include "Pose.hpp"

namespace syropod_highlevel_controller {
template <class ContainerAllocator>
struct LegState_ {

    typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
    _name_type name;

    typedef ::geometry_msgs::PoseStamped_<ContainerAllocator> _walker_tip_pose_type;
    _walker_tip_pose_type walker_tip_pose;

    typedef ::geometry_msgs::PoseStamped_<ContainerAllocator> _target_tip_pose_type;
    _target_tip_pose_type target_tip_pose;

    typedef ::geometry_msgs::PoseStamped_<ContainerAllocator> _poser_tip_pose_type;
    _poser_tip_pose_type poser_tip_pose;

    typedef ::geometry_msgs::PoseStamped_<ContainerAllocator> _model_tip_pose_type;
    _model_tip_pose_type model_tip_pose;

    typedef ::geometry_msgs::PoseStamped_<ContainerAllocator> _actual_tip_pose_type;
    _actual_tip_pose_type actual_tip_pose;

    typedef ::geometry_msgs::TwistStamped_<ContainerAllocator> _model_tip_velocity_type;
    _model_tip_velocity_type model_tip_velocity;

    typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_positions_type;
    _joint_positions_type joint_positions;

    typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_velocities_type;
    _joint_velocities_type joint_velocities;

    typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_efforts_type;
    _joint_efforts_type joint_efforts;

    typedef double _stance_progress_type;
    _stance_progress_type stance_progress;

    typedef double _swing_progress_type;
    _swing_progress_type swing_progress;

    typedef double _time_to_swing_end_type;
    _time_to_swing_end_type time_to_swing_end;

    typedef ::geometry_msgs::Pose_<ContainerAllocator> _pose_delta_type;
    _pose_delta_type pose_delta;

    typedef ::geometry_msgs::Pose_<ContainerAllocator> _auto_pose_type;
    _auto_pose_type auto_pose;

    typedef ::geometry_msgs::Vector3_<ContainerAllocator> _tip_force_type;
    _tip_force_type tip_force;

    typedef ::geometry_msgs::Vector3_<ContainerAllocator> _admittance_delta_type;
    _admittance_delta_type admittance_delta;

    typedef double _virtual_stiffness_type;
    _virtual_stiffness_type virtual_stiffness;

}; // struct LegState

typedef ::syropod_highlevel_controller::LegState_<std::allocator<void>> LegState;

} // namespace syropod_highlevel_controller
#endif // SYROPOD_HIGHLEVEL_CONTROLLER_MESSAGE_LEGSTATE_H
